services:
  - type: web
    name: employee-anniversaries-web
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: npm ci && rm -rf prisma/migrations && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: employee-anniversaries-db
          property: connectionString
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: MANAGER_EMAILS
        value: "manager1@example.com,manager2@example.com"

  - type: cron
    name: employee-anniversaries-daily-cron
    schedule: "0 8 * * *" # daily at 08:00
    runtime: image
    plan: starter
    region: frankfurt
    image:
      url: curlimages/curl:8.6.0
    startCommand: bash -lc "curl -sSf \"https://$WEB_HOST/api/schedule/run-daily\" || true"
    envVars:
      - key: WEB_HOST
        fromService:
          name: employee-anniversaries-web
          type: web
          property: host

databases:
  - name: employee-anniversaries-db
    plan: free
    region: frankfurt
